FROM postgres

ADD /init/00_shared_create_user.sh /docker-entrypoint-initdb.d/
ADD /init/01_shared_create_db.sh /docker-entrypoint-initdb.d/
ADD /init/02_airflow_create_user.sh /docker-entrypoint-initdb.d/
ADD /init/03_airflow_create_db.sh /docker-entrypoint-initdb.d/

USER root

RUN chmod +x /docker-entrypoint-initdb.d/00_shared_create_user.sh
RUN chmod +x /docker-entrypoint-initdb.d/01_shared_create_db.sh
RUN chmod +x /docker-entrypoint-initdb.d/02_airflow_create_user.sh
RUN chmod +x /docker-entrypoint-initdb.d/03_airflow_create_db.sh